#!/usr/bin/env python3
class Exception():

    def generate_scores(self, input):
        def_score = {k : 0 for k in input.keys()}
        off_score = {k : 0 for k in input.keys()}
        return [def_score, off_score]
raise ValueError ("An error was made")